### ISSUE TITLE
Capturing all errors in node?

### ISSUE THREAD

**Issue by rickbutton** [vadimdemedes/yoga-layout-prebuilt#4]
Hi!

I noticed that the emscripten output in this package uses node error wrapping, which swallows all errors  in the application. This usually means that you lose all stack traces when an uncaught exception occurs.

[According to this](https://github.com/emscripten-core/emscripten/issues/5957) you should be able to set `NODEJS_CATCH_EXIT = 0` in order to disable this and restore uncaught exception handling.

If you are ok with this change I would love to submit a patch.

**Comment by vadimdemedes** [comment]
This package is just distributing built version of Yoga, so you should open this issue on Yoga' repository instead.

**Comment by joshkay** [comment]
I'm in the same boat as @rickbutton.  I am currently using @react-pdf/renderer that uses this package and yoga is swallowing all of my uncaught exceptions.  Do you have any ideas how to workaround this?
