### ISSUE TITLE
Add index.d.ts file to allow usage with typescript

### ISSUE THREAD

**Issue by twick00** [vadimdemedes/yoga-layout-prebuilt#6]
When using this with typescript projects, any import from `yoga-layout-prebuilt` resolves to an implicit `any` type. It would be super helpful if you could add a `index.d.ts` file along with this to allow us TypeScript users to ingest this.

**Comment by gkurt** [comment]
The workaround that works for me is, installing `@types/yoga-layout` and creating a `yoga-typed.ts` file with this content:

```
import * as YogaPrebuilt from 'yoga-layout-prebuilt';
import type * as Yoga from 'yoga-layout';

var yoga = YogaPrebuilt as typeof Yoga;

export default yoga;
```

**Comment by twick00** [comment]
My preferred way of using this is to simply override the dependency in the package.json:
```
"devDependencies": {
  "@types/yoga-layout": "^1.9.1"
},
"dependencies": {
  "yoga-layout": "github:vadimdemedes/yoga-layout-prebuilt"
}
```

**Comment by wujunchuan** [comment]
I installed `yoga-layout-prebuilt` package as an alias package `yoga-layout`:

```js
yarn add yoga-layout@npm:yoga-layout-prebuilt
```

![image](https://user-images.githubusercontent.com/7511631/110881272-0a97ac80-831b-11eb-91a4-fac3c7a411bb.png)

The index.d.ts file can't work correct. Do you have any idea to resolve that? 
I want to install `yoga-layout-prebuilt` version with `yoga-layout` name. Or I have to change package name to avoid this situation?
